
; FASM SOURCE FILE
; http://flatassembler.net

; <SI>mple <C>ompiler
; includes (code section)

; Copyright © 2000-3000, Andrey A. Meshkov (AL-CHEMIST)
; All rights reserved
;
; http://maalchemist.ru
; http://maalchemist.narod.ru
; maa@maalchemist.ru
; maalchemist@yandex.ru
; maalchemist@gmail.com

; ------------------------------------------------------------------------------

include '..\..\..\x32\SIC32E.ASM'
include '..\..\..\x32\SIC32IDA.ASM'
include '..\..\..\x32\SIC32B.ASM'
include '..\..\..\x32\SIC32C.ASM'
include '..\..\..\x32\SIC32OP.ASM'
include '..\..\..\x32\SIC32U.ASM'
include '..\..\..\x32\SIC32UC.ASM'
include '..\..\..\x32\SIC32UD.ASM'
include '..\..\..\x32\SIC32UF.ASM'
include '..\..\..\x32\SIC32Fu.ASM'
include '..\..\..\x64\SIC64Rand.ASM'
include '..\..\..\x32\SICmt32.ASM'

; ------------------------------------------------------------------------------
