
; FASM SOURCE FILE
; http://flatassembler.net

; <SI>mple <C>ompiler
; includes (release)

; Copyright © 2000-3000, Andrey A. Meshkov (AL-CHEMIST)
; All rights reserved
;
; http://maalchemist.ru
; http://maalchemist.narod.ru
; maa@maalchemist.ru
; maalchemist@yandex.ru
; maalchemist@gmail.com

; ------------------------------------------------------------------------------

include '%INCLUDE%\WIN32A.INC'

include '..\..\..\xCommon\SYSTEM.INC'
include '..\..\..\xCommon\FJXX.INC'
include '..\..\..\xCommon\MSCOFF32.INC'
include '..\..\..\xCommon\PROCS32.INC'
include '..\..\..\xCommon\SIC.ASH'
include '..\..\..\xCommon\SICIDA.ASH'
include '..\..\..\xCommon\SIC.INC'
include '..\..\..\xCommon\SICV.INC'
include '..\..\..\xCommon\SICC.INC'
include '..\..\..\xCommon\SICCa32.INC'

; ------------------------------------------------------------------------------
