
; FASM SOURCE FILE
; http://flatassembler.net

; <SI>mple <C>ompiler
; includes (data section)

; Copyright © 2000-3000, Andrey A. Meshkov (AL-CHEMIST)
; All rights reserved
;
; http://maalchemist.ru
; http://maalchemist.narod.ru
; maa@maalchemist.ru
; maalchemist@yandex.ru
; maalchemist@gmail.com

; ------------------------------------------------------------------------------

include '..\..\..\x32\SIC32V.ASM'
include '..\..\..\x32\SICmt32V.ASM'
include '..\..\..\xCommon\SICC.ASM'
include '..\..\..\xCommon\SICF.ASM'
include '..\..\..\xCommon\SICIDA.ASM'
include '..\..\..\xCommon\SICFuCO.ASM'

; ------------------------------------------------------------------------------
