
; FASM SOURCE FILE
; http://flatassembler.net

; <SI>mple <C>ompiler
; includes (code section)

; Copyright © 2000-3000, Andrey A. Meshkov (AL-CHEMIST)
; All rights reserved
;
; http://maalchemist.ru
; http://maalchemist.narod.ru
; maa@maalchemist.ru
; maalchemist@yandex.ru
; maalchemist@gmail.com

; ------------------------------------------------------------------------------

include '..\..\..\x64\SIC64E.ASM'
include '..\..\..\x64\SIC64IDA.ASM'
include '..\..\..\x64\SIC64B.ASM'
include '..\..\..\x64\SIC64C.ASM'
include '..\..\..\x64\SIC64OP.ASM'
include '..\..\..\x64\SIC64U.ASM'
include '..\..\..\x64\SIC64UC.ASM'
include '..\..\..\x64\SIC64UD.ASM'
include '..\..\..\x64\SIC64UF.ASM'
include '..\..\..\x64\SIC64Fu.ASM'
include '..\..\..\x64\SIC64Rand.ASM'
include '..\..\..\x64\SICmt64.ASM'

; ------------------------------------------------------------------------------
