{------------------------------------------------------------------------------}

{$IFDEF VER80}                  { Delphi 1.0 }
  {$DEFINE DELPHI_1}
{$ENDIF}

{$IFDEF VER90}                  { Delphi 2.0 }
  {$DEFINE DELPHI_2}
{$ENDIF}

{$IFDEF VER100}                 { Delphi 3.0 }
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER120}                 { Delphi 4.0 }
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER130}                 { Delphi 5.0 }
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER140}                 { Delphi 6.0 }
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER150}                 { Delphi 7.0 }
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER160}                 { Delphi 8.0 }
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER170}                 { Delphi 9.0 (2005) }
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER180}                 { Delphi 10.0 (2006) }
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER185}                 { Delphi 11.0 (2007) }
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER190}                 { Delphi 11.0 (2007) for .Net }
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER200}                 { Delphi 12.0 (2009) }
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER210}                 { Delphi 14.0 (2010) }
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER220}                 { Delphi 15.0 (XE) }
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER230}                 { Delphi 16.0 (XE2) }
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER240}                 { Delphi 17.0 (XE3) }
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER250}                 { Delphi 18.0 (XE4) }
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER260}                 { Delphi 19.0 (XE5) }
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER270}                 { Delphi 20.0 (XE6) }
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER280}                 { Delphi 21.0 (XE7) }
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER290}                 { Delphi 22.0 (XE8) }
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER300}                 { Delphi 23.0 (DX10) }
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER310}                 { Delphi 24.0 (DX10.1) }
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER320}                 { Delphi 25.0 (DX10.2) }
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER330}                 { Delphi 26.0 (DX10.3) }
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER340}                 { Delphi 27.0 (DX10.4) }
  {$DEFINE DELPHI_DX104}
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER350}                 { Delphi 28.0 (DX11) }
  {$DEFINE DELPHI_DX11}
  {$DEFINE DELPHI_DX104}
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER360}                 { Delphi 29.0 (DX12) }
  {$DEFINE DELPHI_DX12}
  {$DEFINE DELPHI_DX11}
  {$DEFINE DELPHI_DX104}
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER370}                 { Delphi 30.0 (DX14) }
  {$DEFINE DELPHI_DX14}
  {$DEFINE DELPHI_DX12}
  {$DEFINE DELPHI_DX11}
  {$DEFINE DELPHI_DX104}
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{$IFDEF VER380}                 { Delphi 31.0 (DX15) }
  {$DEFINE DELPHI_DX15}
  {$DEFINE DELPHI_DX14}
  {$DEFINE DELPHI_DX12}
  {$DEFINE DELPHI_DX11}
  {$DEFINE DELPHI_DX104}
  {$DEFINE DELPHI_DX103}
  {$DEFINE DELPHI_DX102}
  {$DEFINE DELPHI_DX101}
  {$DEFINE DELPHI_DX10}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE6}
  {$DEFINE DELPHI_XE5}
  {$DEFINE DELPHI_XE4}
  {$DEFINE DELPHI_XE3}
  {$DEFINE DELPHI_XE2}
  {$DEFINE DELPHI_XE}
  {$DEFINE DELPHI_2010}
  {$DEFINE DELPHI_2009}
  {$DEFINE DELPHI_2007N}
  {$DEFINE DELPHI_2007}
  {$DEFINE DELPHI_2006}
  {$DEFINE DELPHI_2005}
  {$DEFINE DELPHI_8}
  {$DEFINE DELPHI_7}
  {$DEFINE DELPHI_6}
  {$DEFINE DELPHI_5}
  {$DEFINE DELPHI_4}
  {$DEFINE DELPHI_3}
{$ENDIF}

{------------------------------------------------------------------------------}

{$IFDEF VER80}
  {$DEFINE VER_D1}              { Delphi 1.0 }

  {$DEFINE VER_D1L}             { Delphi 1.0 or lower }
  {$DEFINE VER_D2L}             { Delphi 2.0 or lower }
  {$DEFINE VER_D3L}             { Delphi 3.0 or lower }
  {$DEFINE VER_D4L}             { Delphi 4.0 or lower }
  {$DEFINE VER_D5L}             { Delphi 5.0 or lower }
  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD2}             { lower than Delphi 2.0 }
  {$DEFINE VER_LD3}             { lower than Delphi 3.0 }
  {$DEFINE VER_LD4}             { lower than Delphi 4.0 }
  {$DEFINE VER_LD5}             { lower than Delphi 5.0 }
  {$DEFINE VER_LD6}             { lower than Delphi 6.0 }
  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER90}
  {$DEFINE VER_D2}              { Delphi 2.0 }

  {$DEFINE VER_D2L}             { Delphi 2.0 or lower }
  {$DEFINE VER_D3L}             { Delphi 3.0 or lower }
  {$DEFINE VER_D4L}             { Delphi 4.0 or lower }
  {$DEFINE VER_D5L}             { Delphi 5.0 or lower }
  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD3}             { lower than Delphi 3.0 }
  {$DEFINE VER_LD4}             { lower than Delphi 4.0 }
  {$DEFINE VER_LD5}             { lower than Delphi 5.0 }
  {$DEFINE VER_LD6}             { lower than Delphi 6.0 }
  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER100}
  {$DEFINE VER_D3}              { Delphi 3.0 }

  {$DEFINE VER_D3L}             { Delphi 3.0 or lower }
  {$DEFINE VER_D4L}             { Delphi 4.0 or lower }
  {$DEFINE VER_D5L}             { Delphi 5.0 or lower }
  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD4}             { lower than Delphi 4.0 }
  {$DEFINE VER_LD5}             { lower than Delphi 5.0 }
  {$DEFINE VER_LD6}             { lower than Delphi 6.0 }
  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER120}
  {$DEFINE VER_D4}              { Delphi 4.0 }

  {$DEFINE VER_D4L}             { Delphi 4.0 or lower }
  {$DEFINE VER_D5L}             { Delphi 5.0 or lower }
  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD5}             { lower than Delphi 5.0 }
  {$DEFINE VER_LD6}             { lower than Delphi 6.0 }
  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER130}
  {$DEFINE VER_D5}              { Delphi 5.0 }

  {$DEFINE VER_D5L}             { Delphi 5.0 or lower }
  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD6}             { lower than Delphi 6.0 }
  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER140}
  {$DEFINE VER_D6}              { Delphi 6.0 }

  {$DEFINE VER_D6L}             { Delphi 6.0 or lower }
  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD7}             { lower than Delphi 7.0 }
  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER150}
  {$DEFINE VER_D7}              { Delphi 7.0 }

  {$DEFINE VER_D7L}             { Delphi 7.0 or lower }
  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD8}             { lower than Delphi 8.0 }
  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER160}
  {$DEFINE VER_D8}              { Delphi 8.0 }

  {$DEFINE VER_D8L}             { Delphi 8.0 or lower }
  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD9}             { lower than Delphi 9.0 (2005) }
  {$DEFINE VER_LD2005}
  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER170}
  {$DEFINE VER_D9}              { Delphi 9.0 (2005) }
  {$DEFINE VER_D2005}

  {$DEFINE VER_D9L}             { Delphi 9.0 (2005) or lower }
  {$DEFINE VER_D2005L}
  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD10}            { lower than Delphi 10.0 (2006) }
  {$DEFINE VER_LD2006}
  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER180}
  {$DEFINE VER_D10}             { Delphi 10.0 (2006) }
  {$DEFINE VER_D2006}

  {$DEFINE VER_D10L}            { Delphi 10.0 (2006) or lower }
  {$DEFINE VER_D2006L}
  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD11}            { lower than Delphi 11.0 (2007) }
  {$DEFINE VER_LD2007}
  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net}
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER185}
  {$DEFINE VER_D11}             { Delphi 11.0 (2007) }
  {$DEFINE VER_D2007}

  {$DEFINE VER_D11L}            { Delphi 11.0 (2007) or lower }
  {$DEFINE VER_D2007L}
  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD11N}           { lower than Delphi 11.0 (2007) for .Net }
  {$DEFINE VER_LD2007N}
  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER190}
  {$DEFINE VER_D11N}            { Delphi 11.0 (2007) for .Net }
  {$DEFINE VER_D2007N}

  {$DEFINE VER_D11NL}           { Delphi 11.0 (2007) for .Net or lower }
  {$DEFINE VER_D2007NL}
  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD12}            { lower than Delphi 12.0 (2009) }
  {$DEFINE VER_LD2009}
  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER200}
  {$DEFINE VER_D12}             { Delphi 12.0 (2009) }
  {$DEFINE VER_D2009}

  {$DEFINE VER_D12L}            { Delphi 12.0 (2009) or lower }
  {$DEFINE VER_D2009L}
  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD14}            { lower than Delphi 14.0 (2010) }
  {$DEFINE VER_LD2010}
  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER210}
  {$DEFINE VER_D14}             { Delphi 14.0 (2010) }
  {$DEFINE VER_D2010}

  {$DEFINE VER_D14L}            { Delphi 14.0 (2010) or lower }
  {$DEFINE VER_D2010L}
  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD15}            { lower than Delphi 15.0 (XE) }
  {$DEFINE VER_LDXE}
  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER220}
  {$DEFINE VER_D15}             { Delphi 15.0 (XE) }
  {$DEFINE VER_DXE}

  {$DEFINE VER_D15L}            { Delphi 15.0 (XE) or lower }
  {$DEFINE VER_DXEL}
  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD16}            { lower than Delphi 16.0 (XE2) }
  {$DEFINE VER_LDXE2}
  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER230}
  {$DEFINE VER_D16}             { Delphi 16.0 (XE2) }
  {$DEFINE VER_DXE2}

  {$DEFINE VER_D16L}            { Delphi 16.0 (XE2) or lower }
  {$DEFINE VER_DXE2L}
  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD17}            { lower than Delphi 17.0 (XE3) }
  {$DEFINE VER_LDXE3}
  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER240}
  {$DEFINE VER_D17}             { Delphi 17.0 (XE3) }
  {$DEFINE VER_DXE3}

  {$DEFINE VER_D17L}            { Delphi 17.0 (XE3) or lower }
  {$DEFINE VER_DXE3L}
  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD18}            { lower than Delphi 18.0 (XE4) }
  {$DEFINE VER_LDXE4}
  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER250}
  {$DEFINE VER_D18}             { Delphi 18.0 (XE4) }
  {$DEFINE VER_DXE4}

  {$DEFINE VER_D18L}            { Delphi 18.0 (XE4) or lower }
  {$DEFINE VER_DXE4L}
  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD19}            { lower than Delphi 19.0 (XE5) }
  {$DEFINE VER_LDXE5}
  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER260}
  {$DEFINE VER_D19}             { Delphi 19.0 (XE5) }
  {$DEFINE VER_DXE5}

  {$DEFINE VER_D19L}            { Delphi 19.0 (XE5) or lower }
  {$DEFINE VER_DXE5L}
  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD20}            { lower than Delphi 20.0 (XE6) }
  {$DEFINE VER_LDXE6}
  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER270}
  {$DEFINE VER_D20}             { Delphi 20.0 (XE6) }
  {$DEFINE VER_DXE6}

  {$DEFINE VER_D20L}            { Delphi 20.0 (XE6) or lower }
  {$DEFINE VER_DXE6L}
  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD21}            { lower than Delphi 21.0 (XE7) }
  {$DEFINE VER_LDXE7}
  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER280}
  {$DEFINE VER_D21}             { Delphi 21.0 (XE7) }
  {$DEFINE VER_DXE7}

  {$DEFINE VER_D21L}            { Delphi 21.0 (XE7) or lower }
  {$DEFINE VER_DXE7L}
  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD22}            { lower than Delphi 22.0 (XE8) }
  {$DEFINE VER_LDXE8}
  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER290}
  {$DEFINE VER_D22}             { Delphi 22.0 (XE8) }
  {$DEFINE VER_DXE8}

  {$DEFINE VER_D22L}            { Delphi 22.0 (XE8) or lower }
  {$DEFINE VER_DXE8L}
  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD23}            { lower than Delphi 23.0 (DX10) }
  {$DEFINE VER_LDX10}
  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER300}
  {$DEFINE VER_D23}             { Delphi 23.0 (DX10) }
  {$DEFINE VER_DX10}

  {$DEFINE VER_D23L}            { Delphi 23.0 (DX10) or lower }
  {$DEFINE VER_DX10L}
  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 28.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD24}            { lower than Delphi 24.0 (DX10.1) }
  {$DEFINE VER_LDX101}
  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER310}
  {$DEFINE VER_D24}             { Delphi 24.0 (DX10.1) }
  {$DEFINE VER_DX101}

  {$DEFINE VER_D24L}            { Delphi 24.0 (DX10.1) or lower }
  {$DEFINE VER_DX101L}
  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD25}            { lower than Delphi 25.0 (DX10.2) }
  {$DEFINE VER_LDX102}
  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER320}
  {$DEFINE VER_D25}             { Delphi 25.0 (DX10.2) }
  {$DEFINE VER_DX102}

  {$DEFINE VER_D25L}            { Delphi 25.0 (DX10.2) or lower }
  {$DEFINE VER_DX102L}
  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD26}            { lower than Delphi 26.0 (DX10.3) }
  {$DEFINE VER_LDX103}
  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER330}
  {$DEFINE VER_D26}             { Delphi 26.0 (DX10.3) }
  {$DEFINE VER_DX103}

  {$DEFINE VER_D26L}            { Delphi 26.0 (DX10.3) or lower }
  {$DEFINE VER_DX103L}
  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD27}            { lower than Delphi 27.0 (DX10.4) }
  {$DEFINE VER_LDX104}
  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER340}
  {$DEFINE VER_D27}             { Delphi 27.0 (DX10.4) }
  {$DEFINE VER_DX104}

  {$DEFINE VER_D27L}            { Delphi 27.0 (DX10.4) or lower }
  {$DEFINE VER_DX104L}
  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD28}            { lower than Delphi 28.0 (DX11) }
  {$DEFINE VER_LDX11}
  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER350}
  {$DEFINE VER_D28}             { Delphi 28.0 (DX11) }
  {$DEFINE VER_DX11}

  {$DEFINE VER_D28L}            { Delphi 28.0 (DX11) or lower }
  {$DEFINE VER_DX11L}
  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD29}            { lower than Delphi 29.0 (DX12) }
  {$DEFINE VER_LDX12}
  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER360}
  {$DEFINE VER_D29}             { Delphi 29.0 (DX12) }
  {$DEFINE VER_DX12}

  {$DEFINE VER_D29L}            { Delphi 29.0 (DX12) or lower }
  {$DEFINE VER_DX12L}
  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD30}            { lower than Delphi 30.0 (DX14) }
  {$DEFINE VER_LDX14}
  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER370}
  {$DEFINE VER_D30}             { Delphi 30.0 (DX14) }
  {$DEFINE VER_DX14}

  {$DEFINE VER_D30L}            { Delphi 30.0 (DX14) or lower }
  {$DEFINE VER_DX14L}
  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}

  {$DEFINE VER_LD31}            { lower than Delphi 31.0 (DX15) }
  {$DEFINE VER_LDX15}
{$ENDIF}

{$IFDEF VER380}
  {$DEFINE VER_D31}             { Delphi 31.0 (DX15) }
  {$DEFINE VER_DX15}

  {$DEFINE VER_D31L}            { Delphi 31.0 (DX15) or lower }
  {$DEFINE VER_DX15L}
{$ENDIF}

{$IFNDEF VER80}                 { not Delphi 1.0 }
  {$DEFINE VER_D2H}             { Delphi 2.0 or higher }
{$IFNDEF VER90}                 { not Delphi 2.0 }
  {$DEFINE VER_D3H}             { Delphi 3.0 or higher }
{$IFNDEF VER100}                { not Delphi 3.0 }
  {$DEFINE VER_D4H}             { Delphi 4.0 or higher }
{$IFNDEF VER120}                { not Delphi 4.0 }
  {$DEFINE VER_D5H}             { Delphi 5.0 or higher }
{$IFNDEF VER130}                { not Delphi 5.0 }
  {$DEFINE VER_D6H}             { Delphi 6.0 or higher }
{$IFNDEF VER140}                { not Delphi 6.0 }
  {$DEFINE VER_D7H}             { Delphi 7.0 or higher }
{$IFNDEF VER150}                { not Delphi 7.0 }
  {$DEFINE VER_D8H}             { Delphi 8.0 or higher }
{$IFNDEF VER160}                { not Delphi 8.0 }
  {$DEFINE VER_D9H}             { Delphi 9.0 (2005) or higher }
  {$DEFINE VER_D2005H}
{$IFNDEF VER170}                { not Delphi 9.0 }
  {$DEFINE VER_D10H}            { Delphi 10.0 (2006) or higher }
  {$DEFINE VER_D2006H}
{$IFNDEF VER180}                { not Delphi 10.0 }
  {$DEFINE VER_D11H}            { Delphi 11.0 (2007) or higher }
  {$DEFINE VER_D2007H}
{$IFNDEF VER185}                { not Delphi 11.0 }
  {$DEFINE VER_D11NH}           { Delphi 11.0 (2007) for .Net or higher }
  {$DEFINE VER_D2007NH}
{$IFNDEF VER190}                { not Delphi 11.0 for .Net }
  {$DEFINE VER_D12H}            { Delphi 12.0 (2009) or higher }
  {$DEFINE VER_D2009H}
{$IFNDEF VER200}                { not Delphi 12.0 }
  {$DEFINE VER_D14H}            { Delphi 14.0 (2010) or higher }
  {$DEFINE VER_D2010H}
{$IFNDEF VER210}                { not Delphi 14.0 }
  {$DEFINE VER_D15H}            { Delphi 15.0 (XE) or higher }
  {$DEFINE VER_DXEH}
{$IFNDEF VER220}                { not Delphi 15.0 }
  {$DEFINE VER_D16H}            { Delphi 16.0 (XE2) or higher }
  {$DEFINE VER_DXE2H}
{$IFNDEF VER230}                { not Delphi 16.0 }
  {$DEFINE VER_D17H}            { Delphi 17.0 (XE3) or higher }
  {$DEFINE VER_DXE3H}
{$IFNDEF VER240}                { not Delphi 17.0 }
  {$DEFINE VER_D18H}            { Delphi 18.0 (XE4) or higher }
  {$DEFINE VER_DXE4H}
{$IFNDEF VER250}                { not Delphi 18.0 }
  {$DEFINE VER_D19H}            { Delphi 19.0 (XE5) or higher }
  {$DEFINE VER_DXE5H}
{$IFNDEF VER260}                { not Delphi 19.0 }
  {$DEFINE VER_D20H}            { Delphi 20.0 (XE6) or higher }
  {$DEFINE VER_DXE6H}
{$IFNDEF VER270}                { not Delphi 20.0 }
  {$DEFINE VER_D21H}            { Delphi 21.0 (XE7) or higher }
  {$DEFINE VER_DXE7H}
{$IFNDEF VER280}                { not Delphi 21.0 }
  {$DEFINE VER_D22H}            { Delphi 22.0 (XE8) or higher }
  {$DEFINE VER_DXE8H}
{$IFNDEF VER290}                { not Delphi 22.0 }
  {$DEFINE VER_D23H}            { Delphi 23.0 (DX10) or higher }
  {$DEFINE VER_DX10H}
{$IFNDEF VER300}                { not Delphi 23.0 }
  {$DEFINE VER_D24H}            { Delphi 24.0 (DX10.1) or higher }
  {$DEFINE VER_DX101H}
{$IFNDEF VER310}                { not Delphi 24.0 }
  {$DEFINE VER_D25H}            { Delphi 25.0 (DX10.2) or higher }
  {$DEFINE VER_DX102H}
{$IFNDEF VER320}                { not Delphi 25.0 }
  {$DEFINE VER_D26H}            { Delphi 26.0 (DX10.3) or higher }
  {$DEFINE VER_DX103H}
{$IFNDEF VER330}                { not Delphi 26.0 }
  {$DEFINE VER_D27H}            { Delphi 27.0 (DX10.4) or higher }
  {$DEFINE VER_DX104H}
{$IFNDEF VER340}                { not Delphi 27.0 }
  {$DEFINE VER_D28H}            { Delphi 28.0 (DX11) or higher }
  {$DEFINE VER_DX11H}
{$IFNDEF VER350}                { not Delphi 28.0 }
  {$DEFINE VER_D29H}            { Delphi 29.0 (DX12) or higher }
  {$DEFINE VER_DX12H}
{$IFNDEF VER360}                { not Delphi 29.0 }
  {$DEFINE VER_D30H}            { Delphi 30.0 (DX14) or higher }
  {$DEFINE VER_DX14H}
{$IFNDEF VER370}                { not Delphi 30.0 }
  {$DEFINE VER_D31H}            { Delphi 31.0 (DX15) or higher }
  {$DEFINE VER_DX15H}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}
{$ENDIF}

{------------------------------------------------------------------------------}
