
; FASM SOURCE FILE
; http://flatassembler.net

; Copyright © 2000-3000, Andrey A. Meshkov (AL-CHEMIST)
; All rights reserved
;
; http://maalchemist.ru
; http://maalchemist.narod.ru
; maa@maalchemist.ru
; maalchemist@yandex.ru
; maalchemist@gmail.com

; 32-BIT -----------------------------------------------------------------------

  procall FIX stdcall

; 64-BIT -----------------------------------------------------------------------

; procall FIX fastcall
; stdcall FIX fastcall
; cinvoke FIX invoke

; ------------------------------------------------------------------------------
